export {
  type BabelFile,
  type BabelFileMetadata,
  type BabelFileModulesMetadata,
  type BabelFileResult,
  type ConfigAPI,
  type ConfigFunction,
  type ConfigItem,
  createConfigItem,
  type CreateConfigItemOptions,
  DEFAULT_EXTENSIONS,
  type EnvFunction,
  type FileParseCallback,
  type FileResultCallback,
  type GeneratorOptions,
  loadOptions,
  loadPartialConfig,
  loadPartialConfigAsync,
  type MatchPattern,
  type MatchPatternContext,
  type Node,
  type NodePath,
  parse,
  parseAsync,
  type ParseResult,
  type ParserOptions,
  parseSync,
  type PartialConfig,
  type PluginItem,
  type PluginObj,
  type PluginOptions,
  type PluginPass,
  type PluginTarget,
  resolvePlugin,
  resolvePreset,
  type SimpleCacheCallback,
  type SimpleCacheConfigurator,
  type SimpleCacheKey,
  template,
  transform,
  transformAsync,
  type TransformCaller,
  transformFile,
  transformFileAsync,
  transformFileSync,
  transformFromAst,
  transformFromAstAsync,
  transformFromAstSync,
  type TransformOptions,
  transformSync,
  traverse,
  types,
  version,
  type Visitor,
} from '@babel/core';
