export {
  default as BabelPluginReactCompiler,
  compile,
  compileProgram,
  CompilerError,
  CompilerErrorDetail,
  type CompilerErrorDetailOptions,
  type CompilerPipelineValue,
  CompilerSuggestionOperation,
  default,
  Effect,
  type EnvironmentConfig,
  ErrorSeverity,
  type ExternalFunction,
  findDirectiveDisablingMemoization,
  findDirectiveEnablingMemoization,
  type Hook,
  type Logger,
  type LoggerEvent,
  OPT_IN_DIRECTIVES,
  OPT_OUT_DIRECTIVES,
  parseConfigPragmaForTests,
  parsePluginOptions,
  type PluginOptions,
  printFunctionWithOutlined,
  printHIR,
  printReactiveFunction,
  printReactiveFunctionWithOutlined,
  ProgramContext,
  runBabelPluginReactCompiler,
  type SourceLocation,
  validateEnvironmentConfig,
  ValueKind,
} from 'babel-plugin-react-compiler';
